---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    synced_folders:
        ../../../../example: /tmp/example

suites:
- name: default
  run_list: ["recipe[yapc2013-cookbook]"]
  attributes: {}
